{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "502,504" #default is 413,502,503,504
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
  {{ if .Values.ingress.host2 }}
  - hosts:
    - {{ .Values.ingress.host2 }}
  {{ end }}
    {{ if .Values.ingress.cert_secret }}secretName: {{ .Values.ingress.cert_secret }}{{ end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{ if .Values.ingress.host2 }}
    - host: {{ .Values.ingress.host2 }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{ end }}
{{- end }}
