apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  api_client_id_key: {{ .Values.secrets.api_client_id_key | b64enc | quote }}
  api_secret_key: {{ .Values.secrets.api_secret_key | b64enc | quote }}
  auth_provider_key_key: {{ .Values.secrets.auth_provider_key_key | b64enc | quote }}
  auth_provider_secret_key: {{ .Values.secrets.auth_provider_secret_key | b64enc | quote }}
  sentry_dsn: {{ .Values.secrets.sentry_dsn | b64enc | quote }}
  session_secret_key: {{ .Values.secrets.session_secret_key | b64enc | quote }}