---
# Per environment values which override defaults in hmpps-book-secure-move-frontend/values.yaml

generic-service:
  replicaCount: 8

  ingress:
    hosts:
      - bookasecuremove.service.justice.gov.uk
      - hmpps-book-secure-move-frontend-production.apps.cloud-platform.service.justice.gov.uk
      - hmpps-book-secure-move-frontend-production.apps.live-1.cloud-platform.service.justice.gov.uk
    tlsSecretName: hmpps-book-secure-move-frontend-production-cert

  env:
    API_BASE_URL: "https://hmpps-book-secure-move-api-production.apps.cloud-platform.service.justice.gov.uk"
    AUTH_PROVIDER_URL: "https://sign-in.hmpps.service.justice.gov.uk"
    FEATURE_FLAG_ADD_LODGE_BUTTON: "false"
    FEEDBACK_URL: "https://eu.surveymonkey.com/r/3CKYXSC"
    GOOGLE_ANALYTICS_ID: "G-58WMNWR101"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    MOVE_DESIGN_FEEDBACK_URL: "https://eu.surveymonkey.com/r/BKZC8BV"
    NOMIS_ELITE2_API_URL: "https://api.prison.service.justice.gov.uk"
    SENTRY_ENVIRONMENT: "production"
    SERVER_HOST: "bookasecuremove.service.justice.gov.uk"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    hmpps-book-secure-move-frontend-secrets-production:
      API_CLIENT_ID: api_client_id_key
      API_SECRET: api_secret_key
      APPLICATIONINSIGHTS_CONNECTION_STRING: APPLICATIONINSIGHTS_CONNECTION_STRING
      AUTH_PROVIDER_KEY: auth_provider_key_key
      AUTH_PROVIDER_SECRET: auth_provider_secret_key
      CONTENTFUL_SPACE_ID: contentful_space_id
      CONTENTFUL_ACCESS_TOKEN: contentful_access_token
      SENTRY_DSN: sentry_dsn
      SESSION_SECRET: session_secret_key
      ORDNANCE_MAP_API_KEY: ordnance_map_api_key
      ORDNANCE_MAP_API_SECRET: ordnance_map_api_secret
    elasticache-hmpps-book-secure-move-frontend-production:
      REDIS_AUTH_TOKEN: auth_token
      REDIS_HOST: primary_endpoint_address
