# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/hmpps-book-secure-move-frontend
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: false
  host: hmpps-book-secure-move-frontend-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /

env:
  API_AUTH_PATH: "/oauth/token"
  API_BASE_URL: "https://hmpps-book-secure-move-api-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
  API_HEALTHCHECK_PATH: "/ping.xml"
  API_PATH: "/api"
  API_VERSION: "2"
  API_TIMEOUT: "60000"
  AUTH_PROVIDER_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk"
  FEEDBACK_URL: "https://www.research.net/r/5WLH3PX"
  GOOGLE_ANALYTICS_ID: "UA-106741063-11"
  LOG_LEVEL: "debug"
  NODE_ENV: "preprod"
  NOMIS_ELITE2_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
  PROMETHEUS_MOUNTPATH: "/metrics"
  SENTRY_ENVIRONMENT: "preproduction"
  NAMESPACE_SECRETS: "hmpps-book-secure-move-frontend-secrets-preprod"
  REDIS_SECRETS: "elasticache-hmpps-book-secure-move-frontend-preprod"
  SERVER_HOST: "hmpps-book-secure-move-frontend-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
  SUPPORT_EMAIL: "bookasecuremove@digital.justice.gov.uk"
  FEATURE_FLAG_POPULATION_DASHBOARD: "true"
  FEATURE_FLAG_YOUTH_RISK_ASSESSMENT: "true"
  FEATURE_FLAG_YOUTH_RISK_ASSESSMENT_YOI: "true"
