apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmpps-book-secure-move-frontend-deployment-pr-{PR_NUMBER}
  namespace: hmpps-book-secure-move-frontend-staging
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hmpps-book-secure-move-frontend-web-pr-{PR_NUMBER}
  template:
    metadata:
      labels:
        app: hmpps-book-secure-move-frontend-web-pr-{PR_NUMBER}
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: {DOCKER_IMAGE_URL}
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthcheck/ping
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 20
        livenessProbe:
          httpGet:
            path: /healthcheck/ping
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 6

        # non-secret env vars defined in `config_map.yaml`
        envFrom:
          - configMapRef:
              name: hmpps-book-secure-move-frontend-configmap-pr-{PR_NUMBER}
        env:
          # external secrets defined in `secrets.yml`
          - name: API_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: api_client_id_key
          - name: API_SECRET
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: api_secret_key
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: APPLICATIONINSIGHTS_CONNECTION_STRING
          - name: AUTH_PROVIDER_KEY
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: auth_provider_key_key
          - name: AUTH_PROVIDER_SECRET
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: auth_provider_secret_key
          - name: CONTENTFUL_SPACE_ID
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: contentful_space_id
          - name: CONTENTFUL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: contentful_access_token
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: sentry_dsn
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: hmpps-book-secure-move-frontend-secrets-staging
                key: session_secret_key
          - name: ORDNANCE_MAP_API_KEY
            valueFrom:
               secretKeyRef:
                 name: hmpps-book-secure-move-frontend-secrets-staging
                 key: ordnance_map_api_key
          - name: ORDNANCE_MAP_API_SECRET
            valueFrom:
               secretKeyRef:
                 name: hmpps-book-secure-move-frontend-secrets-staging
                 key: ordnance_map_api_secret
          # secrets created by `terraform`
          - name: REDIS_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: elasticache-hmpps-book-secure-move-frontend-staging
                key: auth_token
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: elasticache-hmpps-book-secure-move-frontend-staging
                key: primary_endpoint_address
