apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hmpps-book-secure-move-frontend-ingress-pr-{PR_NUMBER}
  namespace: hmpps-book-secure-move-frontend-staging
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "502,504" #default is 413,502,503,504
    external-dns.alpha.kubernetes.io/set-identifier: hmpps-book-secure-move-frontend-ingress-pr-{PR_NUMBER}-hmpps-book-secure-move-frontend-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Robots-Tag "noindex, nofollow";
spec:
  ingressClassName: default
  tls:
  - hosts:
    - hmpps-book-secure-move-frontend-pr-{PR_NUMBER}.apps.cloud-platform.service.justice.gov.uk
  rules:
  - host: hmpps-book-secure-move-frontend-pr-{PR_NUMBER}.apps.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: hmpps-book-secure-move-frontend-service-pr-{PR_NUMBER}
            port:
              number: 80
