name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "12 6 * * MON-FRI" # Every weekday
jobs:
  security-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v1.0 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
